### ISSUE TITLE
Set http_proxy for storageos binary

### ISSUE THREAD

**Issue by gioppoluca** [storageos/go-cli#130]
I have nodes behind company proxy and cannot reach the  https://discovery.storageos.cloud so cannot have the token.
Aside from installing the discovery service on premise I would also need to know how to set proxy
Thanks
Luca

**Comment by Arau** [comment]
Hi @gioppoluca,

adding to the comment in https://github.com/storageos/go-cli/issues/129 for which there is no way to define your own discovery server url yet, we are checking the http client library to be able to specify a proxy. 

As mentioned in issue/129, I'd recommend to use a JOIN variable based on nodes ip for now.

**Comment by savage-engineer** [comment]
Support for `HTTP_PROXY`/`http_proxy` included in #134
