### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by MatthiasLohr** [storageos/go-cli#150]
Hello,

are you planning to support ARM architectures (e.g. Raspberry Pi)?

Best regards
Matthias

**Comment by domodwyer** [comment]
Hi @MatthiasLohr 

The CLI can be compiled for ARM if you have the [Go toolchain](https://golang.org/doc/install) installed (we don't currently provide binary releases for ARM).

However the StorageOS container doesn't currently support ARM - it's something we're gauging interest in but we have no immediate plans to provide an ARM build - sorry!

Dom

**Comment by caewok** [comment]
I would also be interested in an ARM build. Looking to run it on a cluster of these: https://www.pine64.org/?product=rockpro64-4gb-single-board-computer

**Comment by advancedwebdeveloper** [comment]
@domodwyer , any changes?
