### ISSUE TITLE
bash-completion

### ISSUE THREAD

**Issue by stuartleeks** [storageos/go-cli#71]
bash-completion would be a great addition to the cli.

A first step would be completion of fixed commands, but it would be especially useful to complete dynamic values (e.g. node names)

**Comment by croomes** [comment]
Hi Stuart - we thought so too, but it was marked as a hidden command and not documented anywhere...

try `storageos install-bash-completion`

I've opened https://github.com/storageos/go-cli/pull/72 to un-hide.

We still need to add the dynamic values though - agree this would be very useful.  Will leave this open so we can track.
